services:
  db:
    container_name: booked-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql