### POST register user
POST {{API_URL}}/auth/register
Content-Type: application/json

{
  "email": "jane@example.com",
  "password": "$up3rSecuRe13",
  "display_name": "Jane Smith123"
}

### POST login user
POST {{API_URL}}/auth/login
Content-Type: application/json

{
  "email": "jane@example.com",
  "password": "securepass"
}

### POST oauth authenticate
POST {{API_URL}}/auth/oauth
Content-Type: application/json

{
  "provider": "google",
  "token": "{{PROVIDER_TOKEN}}"
}

### POST logout user
POST {{API_URL}}/auth/logout
Set-Cookie: