### GET all books
GET {{baseUrl}}{{basePath}}/books

### GET get book by ID
GET {{baseUrl}}{{basePath}}/books/1

### POST save book 1
POST {{baseUrl}}{{basePath}}/books
Content-Type: application/json

{
  "title": "Mistborn",
  "author": "Brando Sando",
  "shelf_id": 1
}

### POST save book 2
POST {{baseUrl}}{{basePath}}/books
Content-Type: application/json

{
  "title": "Red Rising",
  "author": "Pierce Brown",
  "shelf_id": 1
}

### DELETE book by ID
DELETE {{baseUrl}}{{basePath}}/books/1

### GET Search google books
GET {{baseUrl}}{{basePath}}/books/search?query=flowers+inauthor:keyes