### GET all books
GET {{API_URL}}/books
Cookie: access_token={{ACCESS_TOKEN}}

### GET get book by ID
GET {{API_URL}}/books/1
Cookie: access_token={{ACCESS_TOKEN}}

### POST save book 1
POST {{API_URL}}/books
Cookie: access_token={{ACCESS_TOKEN}}
Content-Type: application/json

{
  "title": "Mistborn",
  "author": "Brando Sando",
  "shelf_id": 1
}

### POST save book 2
POST {{API_URL}}/books
Cookie: access_token={{ACCESS_TOKEN}}
Content-Type: application/json

{
  "title": "Red Rising",
  "author": "Pierce Brown",
  "shelf_id": 1
}

### DELETE book by ID
DELETE {{API_URL}}/books/1
Cookie: access_token={{ACCESS_TOKEN}}

### POST complete book
POST {{API_URL}}/books/1/complete
Cookie: access_token={{ACCESS_TOKEN}}
Content-Type: application/json

{
  "rating": 5,
  "review": "book"
}
