### GET all shelves
GET {{baseUrl}}{{basePath}}/shelves

### GET get shelf by ID
GET {{baseUrl}}{{basePath}}/shelves/1

### POST add new shelf
POST {{baseUrl}}{{basePath}}/shelves
Content-Type: application/json

{
  "name": "my shelf"
}

### DELETE remove shelf
DELETE {{baseUrl}}{{basePath}}/shelves/1