### GET all shelves
GET {{API_URL}}/shelves
Cookie: access_token={{ACCESS_TOKEN}}

### GET get shelf by ID
GET {{API_URL}}/shelves/1
Cookie: access_token={{ACCESS_TOKEN}}

### POST add new shelf
POST {{API_URL}}/shelves
Cookie: access_token={{ACCESS_TOKEN}}
Content-Type: application/json

{
  "name": "my shelf"
}

### POST add book to a shelf
POST {{API_URL}}/shelves/1/books
Cookie: access_token={{ACCESS_TOKEN}}
Content-Type: application/json

{
  "volume_id": "nPF9n0SwstMC"
}


### DELETE remove shelf
DELETE {{API_URL}}/shelves/1
Cookie: access_token={{ACCESS_TOKEN}}