### GET all shelves
GET {{API_URL}}/shelves

### GET get shelf by ID
GET {{API_URL}}/shelves/1

### POST add new shelf
POST {{API_URL}}/shelves
Content-Type: application/json

{
  "name": "my shelf"
}

### DELETE remove shelf
DELETE {{API_URL}}/shelves/1